#define pr_fmt(fmt) "%s:%s():%d: " fmt, KBUILD_MODNAME, __func__, __LINE__

#include "events.h"

// TODO real values
struct pacct_event pacct_events_efficiency[PACCT_NUM_EVENTS_EFFICIENCY] = {
	// insn retired any
	{ .code = 0x00, .umask = 0x01, .coeff = 0 },
	// mem scheduler block
	{ .code = 0x04, .umask = 0x07, .coeff = 0 },
	// L2 request all
	{ .code = 0x24, .umask = 0x00, .coeff = 0 },
	// L2 request miss
	{ .code = 0x24, .umask = 0x01, .coeff = 0 },
};

#define SCALE_COUNTER(counter) ((s64)((double)PACCT_COEFF_SCALE * (counter)))

struct pacct_event pacct_events_performance[PACCT_NUM_EVENTS_PERFORMANCE] = {
	// tracked_events autogenerated by convertModel.py
	{
		// Thread cycles when thread is not in halt state
		.code = 0x3c,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(-0.00046672079505486076),
	},
	{
		// Number of instructions retired. General Counter - architectural event
		.code = 0xc0,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(0.18945884280287054),
	},
	{
		// All branch instructions retired.
		.code = 0xc4,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(-0.015368553458472317),
	},
	{
		// All mispredicted branch instructions retired.
		.code = 0xc5,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(0.10675746460969125),
	},
	{
		// Number of instructions retired. Fixed Counter - architectural event
		.code = 0x00,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(-0.18693191306843138),
	},
	{
		// Cycles where at least 1 outstanding demand data read request is pending.
		.code = 0x20,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(0.15820412838662976),
	},
	{
		// Demand Data Read requests sent to uncore
		.code = 0x21,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(-16.49016710732011),
	},
	{
		// Non-modified cache lines that are silently dropped by L2 cache.
		.code = 0x26,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(-0.9011257077943191),
	},
};
