#pragma once

#include <linux/list.h>
#include <linux/kref.h>
#include <linux/types.h>
#include <linux/workqueue.h>
#include <linux/proc_fs.h>
#include <linux/seqlock.h>

// Intel Thread Director (ITD)
#define X86_FEATURE_ITD (14 * 32 + 23) /* Intel Thread Director */
#define MSR_IA32_HW_FEEDBACK_THREAD_CONFIG 0x17d4

/* Hardware Feedback Interface MSR configuration bits */
#define HW_FEEDBACK_PTR_VALID_BIT BIT(0)
#define HW_FEEDBACK_CONFIG_HFI_ENABLE_BIT BIT(0)
#define HW_FEEDBACK_CONFIG_ITD_ENABLE_BIT BIT(1)
#define HW_FEEDBACK_THREAD_CONFIG_ENABLE_BIT BIT(0)

#define CPUID_HFI_LEAF 6
#define PACCT_ITD_MAX_CLASSES 8

// Scaling factor for the coefficients in the energy estimation model to allow for fixed-point arithmetic
#define COUNTER_SCALE 100000000 //For fixed point arithmetic
#define SCALE_COUNTER(counter) ((s64)((double)COUNTER_SCALE * (counter)))

// Define the events we want to track with their event codes and umasks
static struct {
	u8 event_code;
	u8 umask;
	s64 coeff; // Coefficient for energy estimation
} tracked_events[] = {
	// tracked_events autogenerated by convertModel.py
	{
		// Thread cycles when thread is not in halt state
		.event_code = 0x3c,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(0.0025449054478549338),
	},
	{
		// Number of instructions retired. General Counter - architectural event
		.event_code = 0xc0,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(-0.002922289591384071),
	},
	{
		// All branch instructions retired.
		.event_code = 0xc4,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(0.001034537512176854),
	},
	{
		// All mispredicted branch instructions retired.
		.event_code = 0xc5,
		.umask = 0x00,
		.coeff = SCALE_COUNTER(-0.9953297240136587),
	},
	{
		// Number of instructions retired. Fixed Counter - architectural event
		.event_code = 0x00,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(0.003169241994353939),
	},
	{
		// Cycles where at least 1 outstanding demand data read request is pending.
		.event_code = 0x20,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(0.0008327786226836792),
	},
	{
		// Demand Data Read requests sent to uncore
		.event_code = 0x21,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(0.012861678862859853),
	},
	{
		// Non-modified cache lines that are silently dropped by L2 cache.
		.event_code = 0x26,
		.umask = 0x01,
		.coeff = SCALE_COUNTER(-0.1042917907300562),
	},
};

#define PACCT_TRACED_EVENT_COUNT ARRAY_SIZE(tracked_events)

struct traced_task {
	struct list_head list;
	struct list_head retire_node; // Node for the retiring_traced_tasks list
	struct kref ref_count; // Reference count for this traced task entry
	pid_t pid;
	bool ready; // If the task is ready to be sampled
	bool retiring; // Flag to indicate if this task is being retired and should not be sampled anymore
	struct perf_event *event[PACCT_TRACED_EVENT_COUNT];

	//Timestamp for power estimation
	u64 better_timestamp_ns;

	// counts for each event, only buffered for the proc filesystem
	s64 counts[PACCT_TRACED_EVENT_COUNT];

	// estimated energy consumption
	s64 energy_uj;

	// estimated power consumption based on wall clock time
	s64 power_mW;

	char comm[TASK_COMM_LEN];

	// ITD classid for this task
	// 0 is unclassified which should not be used
	// other values are assigned by ITD and are meaningful
	u64 itd_classid;
	u64 itd_sample_count;

	// Count of samples for each ITD classid, indexed by classid.
	// This is used to determine the distribution of ITD classifications for this task.
	// large enough to avoid memory overflow
	u64 itd_classid_count[PACCT_ITD_MAX_CLASSES];

	struct proc_dir_entry *process_dir; // Associated file under proc
};

extern struct stats {
	s64 counter[PACCT_TRACED_EVENT_COUNT];
	s64 energy;
	s64 power;
	s64 energy_rapl;
	s64 power_rapl;
} global_stats;

extern seqlock_t global_stats_lock; // Ensure consistent reads via proc filesystem

void print_stats(struct stats *s);

struct traced_task *new_traced_task(pid_t pid);
void release_traced_task(struct kref *kref);
int setup_traced_task(struct traced_task *entry);
struct traced_task *get_or_create_traced_task(pid_t pid, const char *comm,
					      bool create);
struct traced_task *get_traced_task(pid_t pid);

void queue_pacct_setup_work(void);
void queue_pacct_retire_work(void);
void queue_pacct_scan_tasks(void);
void pacct_start_energy_estimator(void);
void pacct_stop_energy_estimator(void);

struct task_struct *get_task_by_pid(pid_t pid);
u64 read_event_count(struct perf_event *ev);
u64 read_event_count_sleepable(struct perf_event *ev);

int powercap_init_caps(void);
void powercap_cleanup_caps(void);
void pacct_powercap_control_step(u64 pkg_power_mW);

// ITD related functions
int intel_hfi_read_classid(u8 *classid);
void pacct_sample_current_itd(void);
void pacct_init_itd(void);
void pacct_exit_itd(void);
